/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppButton: typeof import('./src/components/app/button/AppButton.vue')['default']
    'AppButton.story': typeof import('./src/components/app/button/AppButton.story.vue')['default']
    AppButtonLoader: typeof import('./src/components/app/button/AppButtonLoader.vue')['default']
    AppModal: typeof import('./src/components/app/modal/AppModal.vue')['default']
    'AppModal.story': typeof import('./src/components/app/modal/AppModal.story.vue')['default']
    AppText: typeof import('./src/components/app/text/AppText.vue')['default']
    'AppText.story': typeof import('./src/components/app/text/AppText.story.vue')['default']
    CheckmarkIcon: typeof import('./src/icons/CheckmarkIcon.vue')['default']
    ChevronDownIcon: typeof import('./src/icons/ChevronDownIcon.vue')['default']
    ChevronLeftIcon: typeof import('./src/icons/ChevronLeftIcon.vue')['default']
    ChevronRightIcon: typeof import('./src/icons/ChevronRightIcon.vue')['default']
    ChevronUpIcon: typeof import('./src/icons/ChevronUpIcon.vue')['default']
    CloseIcon: typeof import('./src/icons/CloseIcon.vue')['default']
    ColorGeneratorView: typeof import('./src/color-generator/views/ColorGeneratorView.vue')['default']
    DownloadIcon: typeof import('./src/icons/DownloadIcon.vue')['default']
    EditIcon: typeof import('./src/icons/EditIcon.vue')['default']
    EyeIcon: typeof import('./src/icons/EyeIcon.vue')['default']
    EyeSlashIcon: typeof import('./src/icons/EyeSlashIcon.vue')['default']
    FilterIcon: typeof import('./src/icons/FilterIcon.vue')['default']
    FormError: typeof import('./src/components/form/error/FormError.vue')['default']
    FormInputField: typeof import('./src/components/form/field/FormInputField.vue')['default']
    'FormInputField.story': typeof import('./src/components/form/field/FormInputField.story.vue')['default']
    FormSelect: typeof import('./src/components/form/select/FormSelect.vue')['default']
    'FormSelect.story': typeof import('./src/components/form/select/FormSelect.story.vue')['default']
    FormSelectOption: typeof import('./src/components/form/select/FormSelectOption.vue')['default']
    InfoIcon: typeof import('./src/icons/InfoIcon.vue')['default']
    MinusIcon: typeof import('./src/icons/MinusIcon.vue')['default']
    PlusIcon: typeof import('./src/icons/PlusIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/icons/SearchIcon.vue')['default']
    SortAscendingIcon: typeof import('./src/icons/SortAscendingIcon.vue')['default']
    SortDescendingIcon: typeof import('./src/icons/SortDescendingIcon.vue')['default']
    SortIcon: typeof import('./src/icons/SortIcon.vue')['default']
    ThreeDotsIcon: typeof import('./src/icons/ThreeDotsIcon.vue')['default']
    TransitionExpand: typeof import('./src/components/app/transitions/TransitionExpand.vue')['default']
    UploadIcon: typeof import('./src/icons/UploadIcon.vue')['default']
  }
}
