/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/app/button/AppButton.vue')['default']
    'AppButton.story': typeof import('./src/components/app/button/AppButton.story.vue')['default']
    AppButtonLoader: typeof import('./src/components/app/button/AppButtonLoader.vue')['default']
    AppModal: typeof import('./src/components/app/modal/AppModal.vue')['default']
    'AppModal.story': typeof import('./src/components/app/modal/AppModal.story.vue')['default']
    AppRadioGroup: typeof import('./src/components/app/radio/AppRadioGroup.vue')['default']
    'AppRadioGroup.story': typeof import('./src/components/app/radio/AppRadioGroup.story.vue')['default']
    AppRadioOption: typeof import('./src/components/app/radio/AppRadioOption.vue')['default']
    AppText: typeof import('./src/components/app/text/AppText.vue')['default']
    'AppText.story': typeof import('./src/components/app/text/AppText.story.vue')['default']
    FormError: typeof import('./src/components/form/error/FormError.vue')['default']
    FormInputField: typeof import('./src/components/form/field/FormInputField.vue')['default']
    'FormInputField.story': typeof import('./src/components/form/field/FormInputField.story.vue')['default']
    FormSelect: typeof import('./src/components/form/select/FormSelect.vue')['default']
    'FormSelect.story': typeof import('./src/components/form/select/FormSelect.story.vue')['default']
    FormSelectOption: typeof import('./src/components/form/select/FormSelectOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionExpand: typeof import('./src/components/app/transitions/TransitionExpand.vue')['default']
  }
}
